name: seuratextend
channels:
  - conda-forge
dependencies:
  - _r-mutex=1.0.1=anacondar_1
  - absl-py=2.2.0=pyhd8ed1ab_0
  - anndata=0.11.3=pyhd8ed1ab_0
  - anyio=4.9.0=pyh29332c3_0
  - aom=3.9.1=h7bae524_0
  - appnope=0.1.4=pyhd8ed1ab_1
  - argon2-cffi=23.1.0=pyhd8ed1ab_1
  - argon2-cffi-bindings=21.2.0=py310h493c2e1_5
  - array-api-compat=1.11.2=pyh29332c3_0
  - arrow=1.3.0=pyhd8ed1ab_1
  - asttokens=3.0.0=pyhd8ed1ab_1
  - async-lru=2.0.5=pyh29332c3_0
  - attrs=25.3.0=pyh71513ae_0
  - babel=2.17.0=pyhd8ed1ab_0
  - beautifulsoup4=4.13.3=pyha770c72_0
  - bleach=6.2.0=pyh29332c3_4
  - bleach-with-css=6.2.0=h82add2a_4
  - blosc=1.21.6=h7dd00d9_1
  - brotli=1.1.0=hd74edd7_2
  - brotli-bin=1.1.0=hd74edd7_2
  - brotli-python=1.1.0=py310hb4ad77e_2
  - bwidget=1.10.1=hce30654_0
  - bzip2=1.0.8=h99b78c6_7
  - c-ares=1.34.4=h5505292_0
  - ca-certificates=2025.1.31=hf0a4a13_0
  - cached-property=1.5.2=hd8ed1ab_1
  - cached_property=1.5.2=pyha770c72_1
  - cairo=1.18.4=h6a3b0d2_0
  - cctools_osx-arm64=1010.6=h729f01a_4
  - cellrank=2.0.6=pyhd8ed1ab_1
  - certifi=2025.1.31=pyhd8ed1ab_0
  - cffi=1.17.1=py310h497396d_0
  - charset-normalizer=3.4.1=pyhd8ed1ab_0
  - chex=0.1.8=pyhd8ed1ab_0
  - clang=20.1.1=default_h474c9e2_0
  - clang-20=20.1.1=default_hf90f093_0
  - clang_impl_osx-arm64=20.1.1=h5eafccf_24
  - clang_osx-arm64=20.1.1=h07b0088_24
  - clangxx=20.1.1=default_h1ffe849_0
  - clangxx_impl_osx-arm64=20.1.1=ha504d2d_24
  - clangxx_osx-arm64=20.1.1=h07b0088_24
  - click=8.1.8=pyh707e725_0
  - colorama=0.4.6=pyhd8ed1ab_1
  - comm=0.2.2=pyhd8ed1ab_1
  - compiler-rt=20.1.1=hd2aecb6_0
  - compiler-rt_osx-arm64=20.1.1=h7969c41_0
  - contourpy=1.3.1=py310h7f4e7e6_0
  - cpython=3.10.16=py310hd8ed1ab_1
  - curl=8.12.1=h73640d1_0
  - cycler=0.12.1=pyhd8ed1ab_1
  - dav1d=1.2.1=hb547adb_0
  - debugpy=1.8.13=py310h853098b_0
  - decorator=5.2.1=pyhd8ed1ab_0
  - defusedxml=0.7.1=pyhd8ed1ab_0
  - dm-tree=0.1.9=py310h7fed476_1
  - docrep=0.3.2=pyh44b312d_0
  - et_xmlfile=2.0.0=pyhd8ed1ab_1
  - etils=1.12.2=pyhd8ed1ab_0
  - exceptiongroup=1.2.2=pyhd8ed1ab_1
  - executing=2.1.0=pyhd8ed1ab_1
  - fftw=3.3.10=mpi_mpich_hd148bab_10
  - filelock=3.18.0=pyhd8ed1ab_0
  - flax=0.10.2=pyhd8ed1ab_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_3
  - fontconfig=2.15.0=h1383a14_1
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - fonttools=4.56.0=py310hc74094e_0
  - fqdn=1.5.1=pyhd8ed1ab_1
  - freetype=2.13.3=h1d14073_0
  - fribidi=1.0.10=h27ca646_0
  - fsspec=2025.3.0=pyhd8ed1ab_0
  - future=1.0.0=pyhd8ed1ab_2
  - get-annotations=0.1.2=pyhd8ed1ab_0
  - gfortran_impl_osx-arm64=13.3.0=h0045e9c_1
  - gfortran_osx-arm64=13.3.0=h3c33bd0_1
  - gmp=6.3.0=h7bae524_2
  - gmpy2=2.1.5=py310h805dbd7_3
  - graphite2=1.3.13=hebf3989_1003
  - grpcio=1.71.0=py310h88df0f0_0
  - gsl=2.7=h6e638da_0
  - h11=0.14.0=pyhd8ed1ab_1
  - h2=4.2.0=pyhd8ed1ab_0
  - h5py=3.13.0=nompi_py310h8ca6390_100
  - harfbuzz=10.4.0=hb72c1af_0
  - hdf5=1.14.3=mpi_mpich_h13a04de_9
  - hpack=4.1.0=pyhd8ed1ab_0
  - httpcore=1.0.7=pyh29332c3_1
  - httpx=0.28.1=pyhd8ed1ab_0
  - humanize=4.12.1=pyhd8ed1ab_0
  - hyperframe=6.1.0=pyhd8ed1ab_0
  - hypre=2.32.0=mpi_mpich_h189fe77_1
  - icu=75.1=hfee45f7_0
  - idna=3.10=pyhd8ed1ab_1
  - importlib-metadata=8.6.1=pyha770c72_0
  - importlib_resources=6.5.2=pyhd8ed1ab_0
  - ipykernel=6.29.5=pyh57ce528_0
  - ipython=8.34.0=pyh907856f_0
  - isl=0.26=imath32_h347afa1_101
  - isoduration=20.11.0=pyhd8ed1ab_1
  - jedi=0.19.2=pyhd8ed1ab_1
  - jinja2=3.1.6=pyhd8ed1ab_0
  - joblib=1.4.2=pyhd8ed1ab_1
  - json5=0.10.0=pyhd8ed1ab_1
  - jsonpointer=3.0.0=py310hbe9552e_1
  - jsonschema=4.23.0=pyhd8ed1ab_1
  - jsonschema-specifications=2024.10.1=pyhd8ed1ab_1
  - jsonschema-with-format-nongpl=4.23.0=hd8ed1ab_1
  - jupyter-lsp=2.2.5=pyhd8ed1ab_1
  - jupyter_client=8.6.3=pyhd8ed1ab_1
  - jupyter_core=5.7.2=pyh31011fe_1
  - jupyter_events=0.12.0=pyh29332c3_0
  - jupyter_server=2.15.0=pyhd8ed1ab_0
  - jupyter_server_terminals=0.5.3=pyhd8ed1ab_1
  - jupyterlab=4.3.6=pyhd8ed1ab_0
  - jupyterlab_pygments=0.3.0=pyhd8ed1ab_2
  - jupyterlab_server=2.27.3=pyhd8ed1ab_1
  - kiwisolver=1.4.7=py310h7306fd8_0
  - krb5=1.21.3=h237132a_0
  - lcms2=2.17=h7eeda09_0
  - ld64_osx-arm64=951.9=hcfee506_4
  - legacy-api-wrap=1.4.1=pyhd8ed1ab_0
  - lerc=4.0.0=h9a09cb3_0
  - libabseil=20250127.1=cxx17_h07bc746_0
  - libaec=1.1.3=hebf3989_0
  - libamd=3.3.3=h5087772_7100102
  - libasprintf=0.23.1=h493aca8_0
  - libavif16=1.2.1=hba52f4c_0
  - libblas=3.9.0=31_h10e41b3_openblas
  - libbrotlicommon=1.1.0=hd74edd7_2
  - libbrotlidec=1.1.0=hd74edd7_2
  - libbrotlienc=1.1.0=hd74edd7_2
  - libbtf=2.3.2=h99b4a89_7100102
  - libcamd=3.3.3=h99b4a89_7100102
  - libcblas=3.9.0=31_hb3479ef_openblas
  - libccolamd=3.3.4=h99b4a89_7100102
  - libcholmod=5.3.1=hbba04d7_7100102
  - libclang-cpp20.1=20.1.1=default_hf90f093_0
  - libcolamd=3.3.4=h99b4a89_7100102
  - libcurl=8.12.1=h73640d1_0
  - libcxx=20.1.1=ha82da77_0
  - libcxx-devel=20.1.1=h6dc3340_0
  - libdeflate=1.23=hec38601_0
  - libedit=3.1.20250104=pl5321hafb1f1b_0
  - libev=4.33=h93a5062_2
  - libexpat=2.6.4=h286801f_0
  - libfabric=2.1.0=hce30654_0
  - libfabric1=2.1.0=h5505292_0
  - libffi=3.4.2=h3422bc3_5
  - libgettextpo=0.23.1=h493aca8_0
  - libgfortran=5.0.0=14_2_0_h6c33f7e_1
  - libgfortran-devel_osx-arm64=13.3.0=h5020ebb_1
  - libgfortran5=14.2.0=h6c33f7e_1
  - libglib=2.82.2=hdff4504_1
  - libgrpc=1.71.0=hf667ad3_0
  - libhwloc=2.11.2=default_hbce5d74_1001
  - libiconv=1.18=hfe07756_1
  - libintl=0.23.1=h493aca8_0
  - libjpeg-turbo=3.0.0=hb547adb_1
  - libklu=2.3.5=h4370aa4_7100102
  - liblapack=3.9.0=31_hc9a63f6_openblas
  - libllvm15=15.0.7=h4429f82_5
  - libllvm20=20.1.1=hc4b4ae8_0
  - liblzma=5.6.4=h39f12f2_0
  - libnghttp2=1.64.0=h6d7220d_0
  - libopenblas=0.3.29=openmp_hf332438_0
  - libpng=1.6.47=h3783ad8_0
  - libprotobuf=5.29.3=hccd9074_0
  - libptscotch=7.0.6=hcfc2647_1
  - libre2-11=2024.07.02=hd41c47c_3
  - libscotch=7.0.6=hd10c9a7_1
  - libsodium=1.0.20=h99b78c6_0
  - libspqr=4.3.4=h775d698_7100102
  - libsqlite=3.49.1=h3f77e49_2
  - libssh2=1.11.1=h9cc3647_0
  - libsuitesparseconfig=7.10.1=h4a8fc20_7100102
  - libtiff=4.7.0=h551f018_3
  - libtorch=2.6.0=cpu_generic_h755bf8d_2
  - libumfpack=6.3.5=h7c2c975_7100102
  - libuv=1.50.0=h5505292_0
  - libwebp-base=1.5.0=h2471fea_0
  - libxcb=1.17.0=hdb1d25a_0
  - libxml2=2.13.6=h178c5d8_0
  - libzlib=1.3.1=h8359307_2
  - lightning=2.5.1=pyhd8ed1ab_0
  - lightning-utilities=0.14.2=pyhd8ed1ab_0
  - llvm-openmp=20.1.1=hdb05f8b_1
  - llvm-tools=20.1.1=hd2aecb6_0
  - llvm-tools-20=20.1.1=h87a4c7e_0
  - llvmlite=0.44.0=py310hed9eb73_0
  - loompy=3.0.6=py_0
  - lz4-c=1.10.0=h286801f_1
  - make=4.4.1=hc9fafa5_2
  - markdown=3.6=pyhd8ed1ab_0
  - markdown-it-py=3.0.0=pyhd8ed1ab_1
  - markupsafe=3.0.2=py310hc74094e_1
  - matplotlib=3.7.1=py310hb6292c7_0
  - matplotlib-base=3.7.1=py310h78c5c2f_0
  - matplotlib-inline=0.1.7=pyhd8ed1ab_1
  - mdurl=0.1.2=pyhd8ed1ab_1
  - metis=5.1.0=h15f6cfe_1007
  - mistune=3.1.3=pyh29332c3_0
  - ml-collections=1.0.0=pyh29332c3_0
  - ml_dtypes=0.5.1=py310h5936506_0
  - mpc=1.3.1=h8f1351a_1
  - mpfr=4.2.1=hb693164_3
  - mpi=1.0.1=mpich
  - mpi4py=4.0.3=py310h8a9557c_0
  - mpich=4.3.0=h9d9a6ae_100
  - mpmath=1.3.0=pyhd8ed1ab_1
  - msgpack-python=1.1.0=py310h7306fd8_0
  - mudata=0.3.1=pyhd8ed1ab_1
  - multipledispatch=0.6.0=pyhd8ed1ab_1
  - mumps-include=5.7.3=h71ed9e6_9
  - mumps-mpi=5.7.3=h2d32478_9
  - munkres=1.1.4=pyh9f0ad1d_0
  - natsort=8.4.0=pyh29332c3_1
  - nbclient=0.10.2=pyhd8ed1ab_0
  - nbconvert-core=7.16.6=pyh29332c3_0
  - nbformat=5.10.4=pyhd8ed1ab_1
  - ncurses=6.5=h5e97a16_3
  - nest-asyncio=1.6.0=pyhd8ed1ab_1
  - networkx=3.4=pyhd8ed1ab_0
  - nomkl=1.0=h5ca1d4c_0
  - notebook-shim=0.2.4=pyhd8ed1ab_1
  - numba=0.61.0=py310h75d646b_1
  - numpy=1.26.4=py310hd45542a_0
  - numpy_groupies=0.11.2=pyhd8ed1ab_1
  - numpyro=0.18.0=pyhd8ed1ab_0
  - openjpeg=2.5.3=h8a3d83b_0
  - openpyxl=3.1.5=py310h0e452f4_1
  - openssl=3.4.1=h81ee809_0
  - opt_einsum=3.4.0=pyhd8ed1ab_1
  - optax=0.2.2=pyhd8ed1ab_0
  - optree=0.14.1=py310h7f4e7e6_1
  - orbax-checkpoint=0.6.4=pyhd8ed1ab_1
  - overrides=7.7.0=pyhd8ed1ab_1
  - packaging=24.2=pyhd8ed1ab_2
  - pandas=1.5.3=py310h2b830bf_1
  - pandocfilters=1.5.0=pyhd8ed1ab_0
  - pango=1.56.3=h73f1e88_0
  - parmetis=4.0.3=ha4b917a_1007
  - parso=0.8.4=pyhd8ed1ab_1
  - patsy=1.0.1=pyhd8ed1ab_1
  - pcre2=10.44=h297a79d_2
  - petsc=3.22.3=real_h8f1400a_103
  - petsc4py=3.22.4=np20py310hdef029b_0
  - pexpect=4.9.0=pyhd8ed1ab_1
  - pickleshare=0.7.5=pyhd8ed1ab_1004
  - pillow=11.1.0=py310h61efb56_0
  - pip=25.0.1=pyh8b19718_0
  - pixman=0.44.2=h2f9eb0b_0
  - pkgutil-resolve-name=1.3.10=pyhd8ed1ab_2
  - platformdirs=4.3.7=pyh29332c3_0
  - progressbar2=4.5.0=pyhd8ed1ab_1
  - prometheus_client=0.21.1=pyhd8ed1ab_0
  - prompt-toolkit=3.0.50=pyha770c72_0
  - protobuf=5.29.3=py310h75f3243_0
  - psutil=7.0.0=py310h078409c_0
  - pthread-stubs=0.4=hd74edd7_1002
  - ptyprocess=0.7.0=pyhd8ed1ab_1
  - pure_eval=0.2.3=pyhd8ed1ab_1
  - pybind11=2.13.6=pyh1ec8472_2
  - pybind11-abi=4=hd8ed1ab_3
  - pybind11-global=2.13.6=pyh415d2e4_2
  - pycparser=2.22=pyh29332c3_1
  - pygam=0.9.1=pyhd8ed1ab_1
  - pygments=2.19.1=pyhd8ed1ab_0
  - pygpcca=1.0.4=pyhd8ed1ab_2
  - pynndescent=0.5.13=pyhd8ed1ab_1
  - pyobjc-core=11.0=py310h4e4eb3c_0
  - pyobjc-framework-cocoa=11.0=py310h4e4eb3c_0
  - pyparsing=3.2.2=pyhd8ed1ab_0
  - pyro-api=0.1.2=pyhd8ed1ab_0
  - pyro-ppl=1.9.1=pyhd8ed1ab_1
  - pysocks=1.7.1=pyha55dd90_7
  - python=3.10.16=h870587a_1_cpython
  - python-dateutil=2.9.0.post0=pyhff2d567_1
  - python-fastjsonschema=2.21.1=pyhd8ed1ab_0
  - python-json-logger=2.0.7=pyhd8ed1ab_0
  - python-utils=3.9.1=pyhff2d567_1
  - python_abi=3.10=5_cp310
  - pytorch=2.6.0=cpu_generic_py310_h8980c24_2
  - pytorch-lightning=2.5.1=pyh506cb10_0
  - pytz=2025.1=pyhd8ed1ab_0
  - pyyaml=6.0.2=py310hc74094e_2
  - pyzmq=26.3.0=py310h6d25ecc_0
  - r-base=4.3.3=h527b63a_16
  - r-lattice=0.22_6=r43h07cda29_1
  - r-matrix=1.6_5=r43hded8dfa_1
  - r-mgcv=1.9_1=r43h83b88f1_1
  - r-nlme=3.1_167=r43he0ea626_0
  - rav1e=0.6.6=h69fbcac_2
  - re2=2024.07.02=h6589ca4_3
  - readline=8.2=h1d1bf99_2
  - referencing=0.36.2=pyh29332c3_0
  - requests=2.32.3=pyhd8ed1ab_1
  - rfc3339-validator=0.1.4=pyhd8ed1ab_1
  - rfc3986-validator=0.1.1=pyh9f0ad1d_0
  - rich=13.9.4=pyhd8ed1ab_1
  - rpds-py=0.23.1=py310h31b3829_0
  - rpy2=3.5.11=py310r43h280b8fa_3
  - scalapack=2.2.0=h71a4f75_4
  - scanpy=1.9.8=pyhd8ed1ab_0
  - scikit-learn=1.1.3=py310ha00a7cd_1
  - scipy=1.15.2=py310h32ab4ed_0
  - scvelo=0.3.3=pyhd8ed1ab_0
  - scvi-tools=1.2.2.post2=pyhd8ed1ab_2
  - seaborn=0.13.2=hd8ed1ab_3
  - seaborn-base=0.13.2=pyhd8ed1ab_3
  - send2trash=1.8.3=pyh31c8845_1
  - session-info=1.0.0=pyhd8ed1ab_0
  - setuptools=75.8.2=pyhff2d567_0
  - sigtool=0.1.3=h44b9a77_0
  - simplegeneric=0.8.1=pyhd8ed1ab_2
  - six=1.17.0=pyhd8ed1ab_0
  - sleef=3.8=h8391f65_0
  - slepc=3.22.2=real_hf0b33f3_300
  - slepc4py=3.22.2=py310h61b750a_0
  - snappy=1.2.1=h98b9ce2_1
  - sniffio=1.3.1=pyhd8ed1ab_1
  - soupsieve=2.5=pyhd8ed1ab_1
  - sparse=0.15.5=pyh72ffeb9_0
  - stack_data=0.6.3=pyhd8ed1ab_1
  - statsmodels=0.14.4=py310hae04be4_0
  - stdlib-list=0.11.1=pyhd8ed1ab_0
  - superlu=7.0.0=h742a510_1
  - superlu_dist=9.1.0=h89afcdd_0
  - svt-av1=3.0.1=h8ab69cd_0
  - sympy=1.13.3=pyh2585a3b_105
  - tapi=1300.6.5=h03f4b80_0
  - tbb=2022.0.0=h0cbf7ec_0
  - tensorboard=2.19.0=pyhd8ed1ab_0
  - tensorboard-data-server=0.7.0=py310hddb97a1_2
  - tensorstore=0.1.65=py310h2bd4c24_5
  - terminado=0.18.1=pyh31c8845_0
  - threadpoolctl=3.6.0=pyhecae5ae_0
  - tinycss2=1.4.0=pyhd8ed1ab_0
  - tk=8.6.13=h5083fa2_1
  - tktable=2.10=h1e387b8_6
  - tomli=2.2.1=pyhd8ed1ab_1
  - toolz=1.0.0=pyhd8ed1ab_1
  - torchmetrics=1.7.0=pyhd8ed1ab_0
  - tornado=6.4.2=py310h078409c_0
  - tqdm=4.67.1=pyhd8ed1ab_1
  - traitlets=5.14.3=pyhd8ed1ab_1
  - types-python-dateutil=2.9.0.20241206=pyhd8ed1ab_0
  - typing-extensions=4.12.2=hd8ed1ab_1
  - typing_extensions=4.12.2=pyha770c72_1
  - typing_utils=0.1.0=pyhd8ed1ab_1
  - tzdata=2025b=h78e105d_0
  - tzlocal=5.3=py310hbe9552e_0
  - umap-learn=0.5.7=py310hbe9552e_1
  - unicodedata2=16.0.0=py310h078409c_0
  - uri-template=1.3.0=pyhd8ed1ab_1
  - urllib3=2.3.0=pyhd8ed1ab_0
  - wcwidth=0.2.13=pyhd8ed1ab_1
  - webcolors=24.11.1=pyhd8ed1ab_0
  - webencodings=0.5.1=pyhd8ed1ab_3
  - websocket-client=1.8.0=pyhd8ed1ab_1
  - werkzeug=3.1.3=pyhd8ed1ab_1
  - wheel=0.45.1=pyhd8ed1ab_1
  - wrapt=1.17.2=py310h078409c_0
  - xarray=2024.3.0=pyhd8ed1ab_0
  - xorg-libxau=1.0.12=h5505292_0
  - xorg-libxdmcp=1.1.5=hd74edd7_0
  - yaml=0.2.5=h3422bc3_2
  - zeromq=4.3.5=hc1bb282_7
  - zipp=3.21.0=pyhd8ed1ab_1
  - zlib=1.3.1=h8359307_2
  - zstandard=0.23.0=py310h078409c_1
  - zstd=1.5.7=h6491c7d_2
  - pip:
      - fcsparser==0.2.8
      - igraph==0.11.8
      - jax==0.5.3
      - jaxlib==0.5.3
      - jaxopt==0.8.3
      - leidenalg==0.10.2
      - mellon==1.6.0
      - palantir==1.3.6
      - texttable==1.7.0
prefix: /Users/frambow/Library/r-miniconda-arm64/envs/seuratextend
